// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using SprintQuiz.Api.Data;

#nullable disable

namespace SprintQuiz.Api.Migrations
{
    [DbContext(typeof(SprintQuizDbContext))]
    [Migration("20250816155302_FirstMigration")]
    partial class FirstMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("SprintQuiz.Api.Models.ConsultationExercice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("AConsulteSolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<bool>("AUtiliseIndices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(false);

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ExerciceId")
                        .HasColumnType("uuid");

                    b.Property<bool?>("MarqueeCompris")
                        .HasColumnType("boolean");

                    b.Property<int>("TentativesAvantSolution")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateConsultation");

                    b.HasIndex("ExerciceId");

                    b.HasIndex("UtilisateurId");

                    b.HasIndex("UtilisateurId", "ExerciceId", "DateConsultation");

                    b.ToTable("ConsultationsExercice");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ConsultationQA", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateConsultation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool?>("MarqueeComprise")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QAQuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("DateConsultation");

                    b.HasIndex("QAQuestionId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("ConsultationsQA");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Cours", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DifficulteMoyenne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DureeEstimee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreExercices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreFlashcards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("NotionsCles")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Objectifs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Resume")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("ModuleId", "Ordre")
                        .IsUnique();

                    b.ToTable("Cours");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.EtapeResolution", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ExerciceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.ToTable("EtapesResolution");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Exercice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Enonce")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NiveauDifficulte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<string>("Solution")
                        .IsRequired()
                        .HasMaxLength(5000)
                        .HasColumnType("character varying(5000)");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SprintId");

                    b.HasIndex("Type");

                    b.HasIndex("Niveau", "NiveauId");

                    b.ToTable("Exercices");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Formation", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DifficulteMoyenne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DureeEstimee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreExercices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreFlashcards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("NotionsCles")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Objectifs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Resume")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Ordre")
                        .IsUnique();

                    b.ToTable("Formations");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Indice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("ExerciceId")
                        .HasColumnType("uuid");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("ExerciceId");

                    b.ToTable("Indices");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Module", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DifficulteMoyenne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DureeEstimee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreExercices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreFlashcards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("NotionsCles")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Objectifs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Resume")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("SprintId", "Ordre")
                        .IsUnique();

                    b.ToTable("Modules");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ProgressionUtilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DerniereActivite")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<float>("PourcentageComplet")
                        .HasColumnType("real");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("FormationId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SprintId");

                    b.HasIndex("UtilisateurId", "Niveau", "NiveauId")
                        .IsUnique();

                    b.ToTable("ProgressionsUtilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QAQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NiveauDifficulte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<string>("Question")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Reponse")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Tags")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SprintId");

                    b.HasIndex("Niveau", "NiveauId");

                    b.ToTable("QAQuestions");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMOption", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("boolean");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<string>("Texte")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("Id");

                    b.HasIndex("QuestionId");

                    b.ToTable("QCMOptions");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMQuestion", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Explication")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Intitule")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("NiveauDifficulte")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("QuizId");

                    b.ToTable("QCMQuestions");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Quiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("CoursId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid?>("ModuleId")
                        .HasColumnType("uuid");

                    b.Property<string>("Niveau")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Guid>("NiveauId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("SprintId")
                        .HasColumnType("uuid");

                    b.Property<string>("Titre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<byte[]>("Version")
                        .IsConcurrencyToken()
                        .IsRequired()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("bytea");

                    b.HasKey("Id");

                    b.HasIndex("CoursId");

                    b.HasIndex("ModuleId");

                    b.HasIndex("SprintId");

                    b.HasIndex("Niveau", "NiveauId");

                    b.ToTable("Quizzes");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ReponseUtilisateurQCM", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<bool>("EstCorrecte")
                        .HasColumnType("boolean");

                    b.Property<Guid>("OptionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("QuestionId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TentativeId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("OptionId");

                    b.HasIndex("QuestionId");

                    b.HasIndex("TentativeId");

                    b.ToTable("ReponsesUtilisateurQCM");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Sprint", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateCreation")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DateOuverture")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DerniereModification")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .HasMaxLength(3000)
                        .HasColumnType("character varying(3000)");

                    b.Property<int>("DifficulteMoyenne")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(1);

                    b.Property<int>("DureeEstimee")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<bool>("EstActif")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true);

                    b.Property<Guid>("FormationId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("NombreExercices")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreFlashcards")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<int>("NombreQuiz")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasDefaultValue(0);

                    b.Property<string>("NotionsCles")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("Objectifs")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("Ordre")
                        .HasColumnType("integer");

                    b.Property<string>("Resume")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Tags")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("FormationId");

                    b.HasIndex("Ordre")
                        .IsUnique();

                    b.ToTable("Sprints");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.StatistiquesGlobales", b =>
                {
                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.Property<int>("CoursTermines")
                        .HasColumnType("integer");

                    b.Property<int>("ModulesTermines")
                        .HasColumnType("integer");

                    b.Property<float>("MoyenneScore")
                        .HasColumnType("real");

                    b.Property<int>("QuestionsQRConsultees")
                        .HasColumnType("integer");

                    b.Property<float>("TauxReussite")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("TempsTotalRevision")
                        .HasColumnType("interval");

                    b.Property<int>("TotalQuiz")
                        .HasColumnType("integer");

                    b.HasKey("UtilisateurId");

                    b.ToTable("StatistiquesGlobales");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.TentativeQuiz", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("Date")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("QuizId")
                        .HasColumnType("uuid");

                    b.Property<bool>("Reussi")
                        .HasColumnType("boolean");

                    b.Property<float>("Score")
                        .HasColumnType("real");

                    b.Property<TimeSpan>("TempsPasse")
                        .HasColumnType("interval");

                    b.Property<Guid>("UtilisateurId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("Date");

                    b.HasIndex("QuizId");

                    b.HasIndex("UtilisateurId");

                    b.ToTable("TentativesQuiz");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Utilisateur", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DateInscription")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("MotDePasse")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Nom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PhotoUrl")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Utilisateurs");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ConsultationExercice", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Exercice", "Exercice")
                        .WithMany("Consultations")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SprintQuiz.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("ConsultationsExercice")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ConsultationQA", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.QAQuestion", "QAQuestion")
                        .WithMany("Consultations")
                        .HasForeignKey("QAQuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SprintQuiz.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("ConsultationsQA")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("QAQuestion");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Cours", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Module", "Module")
                        .WithMany("Cours")
                        .HasForeignKey("ModuleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Module");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.EtapeResolution", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Exercice", "Exercice")
                        .WithMany("EtapesResolution")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Exercice", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Cours", null)
                        .WithMany("Exercices")
                        .HasForeignKey("CoursId");

                    b.HasOne("SprintQuiz.Api.Models.Module", null)
                        .WithMany("Exercices")
                        .HasForeignKey("ModuleId");

                    b.HasOne("SprintQuiz.Api.Models.Sprint", null)
                        .WithMany("Exercices")
                        .HasForeignKey("SprintId");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Indice", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Exercice", "Exercice")
                        .WithMany("Indices")
                        .HasForeignKey("ExerciceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Exercice");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Module", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Sprint", "Sprint")
                        .WithMany("Modules")
                        .HasForeignKey("SprintId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ProgressionUtilisateur", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Cours", "Cours")
                        .WithMany("Progressions")
                        .HasForeignKey("CoursId");

                    b.HasOne("SprintQuiz.Api.Models.Formation", null)
                        .WithMany("Progressions")
                        .HasForeignKey("FormationId");

                    b.HasOne("SprintQuiz.Api.Models.Module", "Module")
                        .WithMany("Progressions")
                        .HasForeignKey("ModuleId");

                    b.HasOne("SprintQuiz.Api.Models.Sprint", "Sprint")
                        .WithMany("Progressions")
                        .HasForeignKey("SprintId");

                    b.HasOne("SprintQuiz.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("Progressions")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cours");

                    b.Navigation("Module");

                    b.Navigation("Sprint");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QAQuestion", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Cours", "Cours")
                        .WithMany("QAQuestions")
                        .HasForeignKey("CoursId");

                    b.HasOne("SprintQuiz.Api.Models.Module", "Module")
                        .WithMany("QAQuestions")
                        .HasForeignKey("ModuleId");

                    b.HasOne("SprintQuiz.Api.Models.Sprint", "Sprint")
                        .WithMany("QAQuestions")
                        .HasForeignKey("SprintId");

                    b.Navigation("Cours");

                    b.Navigation("Module");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMOption", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.QCMQuestion", "Question")
                        .WithMany("Options")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Question");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMQuestion", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Quiz", "Quiz")
                        .WithMany("Questions")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Quiz", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Cours", "Cours")
                        .WithMany("Quizzes")
                        .HasForeignKey("CoursId");

                    b.HasOne("SprintQuiz.Api.Models.Module", "Module")
                        .WithMany("Quizzes")
                        .HasForeignKey("ModuleId");

                    b.HasOne("SprintQuiz.Api.Models.Sprint", "Sprint")
                        .WithMany("Quizzes")
                        .HasForeignKey("SprintId");

                    b.Navigation("Cours");

                    b.Navigation("Module");

                    b.Navigation("Sprint");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.ReponseUtilisateurQCM", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.QCMOption", "Option")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("OptionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SprintQuiz.Api.Models.QCMQuestion", "Question")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("QuestionId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("SprintQuiz.Api.Models.TentativeQuiz", "Tentative")
                        .WithMany("ReponsesUtilisateur")
                        .HasForeignKey("TentativeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Option");

                    b.Navigation("Question");

                    b.Navigation("Tentative");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Sprint", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Formation", "Formation")
                        .WithMany("Sprints")
                        .HasForeignKey("FormationId")
                        .OnDelete(DeleteBehavior.SetNull)
                        .IsRequired();

                    b.Navigation("Formation");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.StatistiquesGlobales", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Utilisateur", "Utilisateur")
                        .WithOne("StatistiquesGlobales")
                        .HasForeignKey("SprintQuiz.Api.Models.StatistiquesGlobales", "UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.TentativeQuiz", b =>
                {
                    b.HasOne("SprintQuiz.Api.Models.Quiz", "Quiz")
                        .WithMany("Tentatives")
                        .HasForeignKey("QuizId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("SprintQuiz.Api.Models.Utilisateur", "Utilisateur")
                        .WithMany("TentativesQuiz")
                        .HasForeignKey("UtilisateurId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Quiz");

                    b.Navigation("Utilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Cours", b =>
                {
                    b.Navigation("Exercices");

                    b.Navigation("Progressions");

                    b.Navigation("QAQuestions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Exercice", b =>
                {
                    b.Navigation("Consultations");

                    b.Navigation("EtapesResolution");

                    b.Navigation("Indices");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Formation", b =>
                {
                    b.Navigation("Progressions");

                    b.Navigation("Sprints");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Module", b =>
                {
                    b.Navigation("Cours");

                    b.Navigation("Exercices");

                    b.Navigation("Progressions");

                    b.Navigation("QAQuestions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QAQuestion", b =>
                {
                    b.Navigation("Consultations");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMOption", b =>
                {
                    b.Navigation("ReponsesUtilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.QCMQuestion", b =>
                {
                    b.Navigation("Options");

                    b.Navigation("ReponsesUtilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Quiz", b =>
                {
                    b.Navigation("Questions");

                    b.Navigation("Tentatives");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Sprint", b =>
                {
                    b.Navigation("Exercices");

                    b.Navigation("Modules");

                    b.Navigation("Progressions");

                    b.Navigation("QAQuestions");

                    b.Navigation("Quizzes");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.TentativeQuiz", b =>
                {
                    b.Navigation("ReponsesUtilisateur");
                });

            modelBuilder.Entity("SprintQuiz.Api.Models.Utilisateur", b =>
                {
                    b.Navigation("ConsultationsExercice");

                    b.Navigation("ConsultationsQA");

                    b.Navigation("Progressions");

                    b.Navigation("StatistiquesGlobales");

                    b.Navigation("TentativesQuiz");
                });
#pragma warning restore 612, 618
        }
    }
}
